version: "3.1"

services:
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - ./redis-data:/data
        environment:
            REDIS_ARGS: --save 300 1 60 10
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        image: vencord/backend
        build: .
        restart: always
        env_file:
            - stack.env
        depends_on:
            redis:
                condition: service_healthy
        environment:
            PORT: 8080
            REDIS_URI: redis:6379
        ports:
            - ${PORT}:8080/tcp
